import { describe, expect, it } from 'vitest';
import { rollExpression } from './rollService';
import { normalizeExpression, type StoredRoll } from './sessionLedger';
import { clearTheoreticalCache, expressionStats, fairness, filterRolls, highlights, hotCold, outcomeDistribution, percentile, playerStats, summary, theoretical, timeline } from './analytics';

let id=0;
function record(expression:string,face:number,player='Joe',time=0):StoredRoll{
  const result=rollExpression({requestId:`roll-${++id}`,expression,visibility:'everyone',playerId:player,playerName:player},{integer:max=>(face-1)%max}).record;
  return {id:result.requestId,sessionId:'session',timestamp:time,rollerId:player,rollerName:player,expression,normalizedExpression:normalizeExpression(result),finalResult:result.value,resolution:result.resolution!,visibility:result.visibility,result};
}
describe('shared session analytics',()=>{
  it('computes box score, ties, activity, and empty states',()=>{const a=record('d6',1,'Joe',0),b=record('d6',6,'Bill',600_000),c=record('d6',3,'Joe',900_000);const data=summary([a,b,c]);expect([data.rolls,data.dice,data.players,data.expressions,data.first,data.last,data.duration]).toEqual([3,3,2,1,0,900_000,900_000]);expect(data.longestGap).toBe(600_000);expect(data.busiestTen.count).toBe(2);expect(data.most?.names).toEqual(['Joe']);expect(summary([a,b]).most?.names).toEqual(['Joe','Bill']);expect(summary([]).perHour).toBeNull();});
  it('uses midpoint percentiles and caches exact distributions',()=>{clearTheoreticalCache();const low=record('d20',1),high=record('2d6+1',6),middle=record('d6',3);expect(percentile(low)?.score).toBeCloseTo(.025);expect(percentile(middle)?.score).toBeCloseTo(2.5/6);expect(percentile(high)?.score).not.toBeNull();expect(percentile(record('2d6',6))?.score).toBeCloseTo(71/72);expect(percentile(record('d6+2',3))?.score).toBeCloseTo(2.5/6);expect(percentile(record('d{1,1,6}',1))?.score).toBeCloseTo(1/3);expect(theoretical(low.normalizedExpression)).toBe(theoretical(low.normalizedExpression));expect(percentile({...low,finalResult:'text'}) as unknown).toBeNull();});
  it('groups players, expressions, dice, and observed outcomes',()=>{const rolls=[record('d6',1,'Joe'),record('d6',6,'Bill'),record('d20',20,'Joe')];expect(filterRolls(rolls,{player:'Joe'})).toHaveLength(2);const players=playerStats(rolls);expect(players.find(p=>p.name==='Joe')).toMatchObject({rolls:2,dice:2,expressions:2,mins:1,maxs:1});expect(expressionStats(rolls).find(e=>e.label.includes('d6'))?.expected).toBeCloseTo(3.5);expect(outcomeDistribution(rolls,'dice','d6').count).toBe(2);expect(outcomeDistribution(rolls,'results').mean).toBe(9);});
  it('requires ten qualifying rolls for hot and cold',()=>{const short=playerStats([record('d6',1,'Joe'),record('d6',6,'Bill')]);expect(hotCold(short)).toBeNull();const long=playerStats([...Array.from({length:10},()=>record('d6',6,'Joe')),...Array.from({length:10},()=>record('d20',1,'Bill'))]);expect(hotCold(long)?.hot[0].name).toBe('Joe');expect(hotCold(long)?.cold[0].name).toBe('Bill');});
  it('buckets empty time and compares frequencies',()=>{const rolls=[record('d6',1,'Joe',0),record('d6',6,'Joe',120_000)];expect(timeline(rolls,60_000).points.map(p=>p.count)).toEqual([1,0,1]);const fair=fairness(rolls,rolls[0].normalizedExpression)!;expect(fair.sample).toBe(2);expect(fair.rows.find(r=>r.value===1)?.observed).toBe(1);expect(fair.rows[0].expected).toBeCloseTo(1/6);expect(highlights(rolls).largest?.resolution.dice).toHaveLength(1);});
  it('finds percentile streaks and explosion chains from structured draws',()=>{const rolls=[record('d6',6,'Joe',0),record('d6',5,'Joe',1),record('d6',6,'Joe',2),record('d6!2',6,'Bill',3)];const reel=highlights(rolls);expect(reel.highStreak?.count).toBe(3);expect(reel.explosion?.count).toBe(2);expect(reel.largest?.resolution.dice).toHaveLength(3);});
  it('caps timeline buckets for long sessions and gives an expected range',()=>{const rolls=[record('d6',1,'Joe',0),record('d6',2,'Joe',86_400_000)];expect(timeline(rolls).points.length).toBeLessThanOrEqual(122);const fair=fairness(rolls,rolls[0].normalizedExpression)!;expect(fair.rows[0].range?.[0]).toBeGreaterThanOrEqual(0);expect(fair.cumulative).toHaveLength(2);});
});
