import { useMemo, useState } from 'react';
import type { StoredRoll } from './sessionLedger';
import { dieType, expressionLabel, expressionStats, fairness, highlights, hotCold, naturalBounds, outcomeDistribution, playerStats, summary, timeline } from './analytics';
import { SequenceTab } from './SequenceTab';

export type AnalyticsTab='overview'|'players'|'expressions'|'outcomes'|'highlights'|'timeline'|'query'|'fairness';
export const tabs:AnalyticsTab[]=['overview','players','expressions','outcomes','highlights','timeline','query','fairness'];
const pct=(v:number|null|undefined)=>v==null?'—':`${(v*100).toFixed(1)}%`;
const n=(v:number|null|undefined)=>v==null?'—':Number.isInteger(v)?String(v):v.toFixed(2);
const when=(v:number|undefined)=>v==null?'—':new Date(v).toLocaleString();
const span=(v:number)=>v<60_000?`${Math.round(v/1000)} sec`:v<3_600_000?`${(v/60_000).toFixed(1)} min`:`${(v/3_600_000).toFixed(1)} hr`;
const event=(r:StoredRoll)=>`${r.rollerName} · ${expressionLabel(r.normalizedExpression)} → ${String(r.finalResult)} · ${when(r.timestamp)}`;
const ranked=(r:{names:string[];count:number}|null)=>r?`${r.names.join(' and ')} — ${r.count}`:'—';
function Table({rows,total}:{rows:{value:number|string;count:number;expected?:number}[];total:number}){const expected=rows.some(r=>r.expected!==undefined);return <div className="stat-scroll"><table><thead><tr><th>Outcome</th><th>Count</th><th>Observed %</th>{expected&&<th>Expected %</th>}</tr></thead><tbody>{rows.slice(0,200).map(r=><tr key={`${typeof r.value}:${r.value}`}><td>{r.value}</td><td>{r.count}</td><td>{pct(total?r.count/total:null)}</td>{expected&&<td>{pct(r.expected)}</td>}</tr>)}</tbody></table>{rows.length>200&&<p>Showing first 200 of {rows.length} outcomes.</p>}</div>;}
function Card({label,value}:{label:string;value:string|number}){return <div className="stat-card"><small>{label}</small><strong>{value}</strong></div>;}
export function AnalyticsTabs({tab,rolls,sessionName,player,expression,onPlayer,onExpression}:{tab:AnalyticsTab;rolls:StoredRoll[];sessionName:string;player:string;expression:string;onPlayer:(v:string)=>void;onExpression:(v:string)=>void}){
  const [mode,setMode]=useState<'results'|'dice'>('results');const [die,setDie]=useState('');const [fairKey,setFairKey]=useState('');
  const box=useMemo(()=>summary(rolls),[rolls]);const players=useMemo(()=>playerStats(rolls),[rolls]);const expressions=useMemo(()=>expressionStats(rolls),[rolls]);const hc=useMemo(()=>hotCold(players),[players]);
  const types=useMemo(()=>[...new Set(rolls.flatMap(r=>r.resolution.dice.map(d=>dieType(r,d))))].sort(),[rolls]);
  const outcomes=useMemo(()=>outcomeDistribution(rolls,mode,mode==='dice'?die||types[0]:undefined),[rolls,mode,die,types]);
  const highlightsData=useMemo(()=>highlights(rolls),[rolls]);const activity=useMemo(()=>timeline(rolls),[rolls]);const fair=useMemo(()=>fairness(rolls,fairKey),[rolls,fairKey]);
  const playerDetail=useMemo(()=>player&&players[0]?{box:summary(players[0].list),events:highlights(players[0].list)}:null,[player,players]);
  if(tab==='query')return <SequenceTab rolls={rolls}/>;
  if(tab==='overview')return <><h2>{sessionName}</h2><div className="headline-stats"><div><strong>{box.rolls}</strong><span>rolls</span></div><div><strong>{box.dice}</strong><span>dice</span></div><div><strong>{box.players}</strong><span>rollers</span></div><div><strong>{box.expressions}</strong><span>expressions</span></div></div><section className="stat-grid"><Card label="First roll" value={when(box.first)}/><Card label="Last roll" value={when(box.last)}/><Card label="Elapsed" value={box.rolls?span(box.duration):'—'}/><Card label="Rolls/hour" value={n(box.perHour)}/><Card label="Most active roller" value={ranked(box.most)}/><Card label="Least active roller" value={ranked(box.least)}/><Card label="Most-used expression" value={ranked(box.expression)}/><Card label="Most common die" value={ranked(box.die)}/><Card label="Longest gap" value={box.rolls>1?span(box.longestGap):'—'}/><Card label="Busiest 10 minutes" value={`${box.busiestTen.count} rolls`}/></section><section><h3>Highest and lowest final results</h3><p>Highest: {box.high.length?box.high.map(event).join(' · '):'No numeric results'}</p><p>Lowest: {box.low.length?box.low.map(event).join(' · '):'No numeric results'}</p></section><section><h3>Hot and cold dice</h3><p className="filter-summary">Average midpoint percentile; at least 10 qualifying numeric rolls per player. Descriptive session data.</p>{hc?.tie?<p>Qualifying players are effectively tied.</p>:hc?<><p>Hot: {hc.hot.map(p=>`${p.name} — ${pct(p.average)}`).join(' and ')}</p><p>Cold: {hc.cold.map(p=>`${p.name} — ${pct(p.average)}`).join(' and ')}</p></>:<p>Not enough qualifying rolls yet.</p>}</section></>;
  if(tab==='players')return <><h2>Players</h2><div className="stat-scroll"><table><thead><tr>{['Player','Rolls','Dice','% of rolls','Expressions','Average percentile','Natural min','Natural max','First roll','Last roll'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{players.map(p=><tr key={p.id} tabIndex={0} onClick={()=>onPlayer(player===p.id?'':p.id)} onKeyDown={e=>{if(e.key==='Enter')onPlayer(player===p.id?'':p.id);}}><td>{p.name}</td><td>{p.rolls}</td><td>{p.dice}</td><td>{pct(box.rolls?p.rolls/box.rolls:null)}</td><td>{p.expressions}</td><td>{pct(p.average)} ({p.qualifying})</td><td>{p.mins}</td><td>{p.maxs}</td><td>{when(p.first)}</td><td>{when(p.last)}</td></tr>)}</tbody></table></div>{player&&players[0]&&<section><Card label="Selected player" value={`${players[0].name}: ${players[0].rolls} rolls, ${players[0].dice} dice, ${pct(players[0].average)} average percentile`}/><p>Most-used expression: {playerDetail?.box.expression?.names.join(", ")??"—"} · Most common die: {playerDetail?.box.die?.names.join(", ")??"—"}</p><p>Natural minimums {players[0].mins} · Natural maximums {players[0].maxs} · High streak {playerDetail?.events.highStreak?.count??"—"} · Low streak {playerDetail?.events.lowStreak?.count??"—"}</p></section>}</>;
  if(tab==='expressions')return <><h2>Expressions</h2><div className="stat-scroll"><table><thead><tr>{['Expression','Rolls','Rollers','Expected mean','Observed mean','Observed min','Observed max'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{expressions.map(e=><tr key={e.id} tabIndex={0} onClick={()=>onExpression(expression===e.id?'':e.id)} onKeyDown={ev=>{if(ev.key==='Enter')onExpression(expression===e.id?'':e.id);}}><td><code>{e.label}</code></td><td>{e.rolls}</td><td>{e.rollers}</td><td>{n(e.expected)}</td><td>{n(e.observed)}</td><td>{n(e.min)}</td><td>{n(e.max)}</td></tr>)}</tbody></table></div>{expression&&expressions[0]&&<section><h3>{expressions[0].label} · {expressions[0].rolls} rolls</h3><p>Theoretical range {expressions[0].range?.join('–')??'unavailable'} · Expected mean {n(expressions[0].expected)} · Observed mean {n(expressions[0].observed)} · Observed range {n(expressions[0].min)}–{n(expressions[0].max)} · Most common {expressions[0].distribution.modes.join(", ")||"—"}</p><p>Players: {[...new Set(expressions[0].list.map(r=>r.rollerName))].join(", ")}</p><Table rows={expressions[0].chart?expressions[0].chart.entries.map(item=>({value:item.value as number,count:expressions[0].distribution.rows.find(r=>r.value===item.value)?.count??0,expected:item.probability})):expressions[0].distribution.rows} total={expressions[0].rolls}/></section>}</>;
  if(tab==='outcomes'){let naturalMin=0,naturalMax=0;for(const r of rolls)for(const d of r.resolution.dice){if(dieType(r,d)!==(die||types[0]))continue;const bounds=naturalBounds(r,d);if(bounds&&typeof d.face==='number'){if(d.face===bounds[0])naturalMin++;if(d.face===bounds[1])naturalMax++;}}const categories=new Map<string,number>();for(const r of rolls){const label=r.result.interpretation;if(label)categories.set(label,(categories.get(label)??0)+1);}return <><h2>Outcomes</h2><div className="mode-tabs"><button type="button" aria-pressed={mode==='results'} onClick={()=>setMode('results')}>Results</button><button type="button" aria-pressed={mode==='dice'} onClick={()=>setMode('dice')}>Dice</button></div>{mode==='dice'&&<label>Die type <select value={types.includes(die)?die:types[0]??''} onChange={e=>setDie(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label>}<p>{outcomes.count} {mode==='dice'?'dice':'results'} · Min {n(outcomes.min)} · Max {n(outcomes.max)} · Mean {n(outcomes.mean)} · Median {n(outcomes.median)} · Mode {outcomes.modes.join(', ')||'—'}</p><Table rows={outcomes.rows} total={outcomes.count}/><section><h3>Interpretation categories</h3>{categories.size?<Table rows={[...categories].map(([value,count])=>({value,count}))} total={rolls.length}/>:<p>No recorded categories.</p>}</section></>;}
  if(tab==='highlights')return <><h2>Highlights</h2><div className="stat-grid">{highlightsData.rare&&<Card label="Long shot" value={`${event(highlightsData.rare.roll)} · About ${pct(highlightsData.rare.tail)} in the nearer inclusive tail.`}/ >}{highlightsData.largest&&<Card label="Largest dice pool" value={`${highlightsData.largest.rollerName}: ${highlightsData.largest.resolution.dice.length} dice`}/ >}{box.high[0]&&<Card label="Highest final result" value={box.high.map(event).join(' · ')}/ >}{box.low[0]&&<Card label="Lowest final result" value={box.low.map(event).join(' · ')}/ >}{highlightsData.highStreak&&<Card label="High streak" value={`${highlightsData.highStreak.roll.rollerName}: ${highlightsData.highStreak.count} qualifying rolls above midpoint`}/ >}{highlightsData.lowStreak&&<Card label="Low streak" value={`${highlightsData.lowStreak.roll.rollerName}: ${highlightsData.lowStreak.count} qualifying rolls below midpoint`}/ >}{highlightsData.naturalMin&&<Card label="Natural minimum streak" value={`${highlightsData.naturalMin.roll.rollerName}: ${highlightsData.naturalMin.count} consecutive die draws`}/ >}{highlightsData.naturalMax&&<Card label="Natural maximum streak" value={`${highlightsData.naturalMax.roll.rollerName}: ${highlightsData.naturalMax.count} consecutive die draws`}/ >}{highlightsData.explosion&&<Card label="Longest explosion chain" value={highlightsData.explosion.roll.rollerName+": "+highlightsData.explosion.count+" additional draws from one die"}/ >}{box.fastestMinute.count>1&&<Card label="Fastest roll burst" value={`${box.fastestMinute.count} rolls within one minute starting ${when(box.fastestMinute.at)}`}/ >}</div>{!rolls.length&&<p>No rolls yet.</p>}</>;
  if(tab==='timeline')return <><h2>Timeline</h2><p className="filter-summary">{span(activity.bucket)} buckets · {box.rolls} rolls</p><div className="activity-chart" role="img" aria-label="Roll activity over time">{activity.points.map(p=><div key={p.time} title={`${when(p.time)}: ${p.count} rolls`} style={{height:`${Math.max(3,p.count/Math.max(1,...activity.points.map(x=>x.count))*100)}%`}}/>)}</div>{!activity.points.length&&<p>No rolls yet.</p>}</>;
  return <><h2>Fairness explorer</h2><p className="filter-summary">Observed frequencies alongside exact theoretical probabilities. No fairness verdict is inferred.</p><label>Comparable expression <select value={fairKey} onChange={e=>setFairKey(e.target.value)}><option value="">Select an expression</option>{expressions.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select></label>{fair?<><p><strong>Sample: {fair.sample} rolls</strong> · Recent window: {fair.recent} of 100</p><Table rows={fair.rows.map(r=>({value:r.value,count:r.observed,expected:r.expected}))} total={fair.sample}/><p className="filter-summary">Expected ranges are approximate 95% binomial ranges for this sample size.</p><div className="stat-scroll"><table><thead><tr><th>Outcome</th><th>Expected range</th></tr></thead><tbody>{fair.rows.slice(0,100).map(r=><tr key={r.value}><td>{r.value}</td><td>{r.range?pct(r.range[0])+'–'+pct(r.range[1]):'—'}</td></tr>)}</tbody></table></div><h3>Cumulative average percentile</h3><div className="activity-chart" role="img" aria-label="Cumulative average midpoint percentile over roll order">{fair.cumulative.filter((_,index)=>index%Math.max(1,Math.ceil(fair.cumulative.length/200))===0).map(point=><div key={point.roll} title={'After '+point.roll+' rolls: '+pct(point.average)} style={{height:String(Math.max(3,point.average*100))+'%'}}/>)}</div><h3>Recent window</h3><Table rows={fair.rolling.map(r=>({value:r.value,count:Math.round(r.rate*fair.recent)}))} total={fair.recent}/></>:fairKey?<p>Exact numeric theoretical distribution unavailable for this expression.</p>:<p>Select one expression to compare like outcomes.</p>}</>;
}
