import { describe, expect, it } from 'vitest';
import { rollExpression } from './rollService';
import { normalizeExpression, type StoredRoll } from './sessionLedger';
import type { Distribution } from './engine/probability';
import { clearTheoreticalCache, expressionStats, fairness, filterRolls, hotCold, outcomeDistribution, percentile, percentileFromDistribution, playerStats, referenceDistribution, summary, theoretical } from './analytics';

let id=0;
function record(expression:string,face:number,player='Joe',time=0):StoredRoll{
  const result=rollExpression({requestId:`roll-${++id}`,expression,visibility:'everyone',playerId:player,playerName:player},{integer:max=>(face-1)%max}).record;
  return {id:result.requestId,sessionId:'session',timestamp:time,rollerId:player,rollerName:player,expression,normalizedExpression:normalizeExpression(result),finalResult:result.value,resolution:result.resolution!,visibility:result.visibility,result};
}
describe('shared session analytics',()=>{
  it('computes box score, ties, activity, and empty states',()=>{const a=record('d6',1,'Joe',0),b=record('d6',6,'Bill',600_000),c=record('d6',3,'Joe',900_000);const data=summary([a,b,c]);expect([data.rolls,data.dice,data.players,data.expressions,data.first,data.last,data.duration]).toEqual([3,3,2,1,0,900_000,900_000]);expect(data.longestGap).toBe(600_000);expect(data.busiestTen.count).toBe(2);expect(data.most?.names).toEqual(['Joe']);expect(summary([a,b]).most?.names).toEqual(['Joe','Bill']);expect(summary([]).perHour).toBeNull();});
  it('uses midpoint percentiles and caches exact distributions',()=>{clearTheoreticalCache();const low=record('d20',1),high=record('2d6+1',6),middle=record('d6',3);expect(percentile(low)?.score).toBeCloseTo(.025);expect(percentile(middle)?.score).toBeCloseTo(2.5/6);expect(percentile(high)?.score).not.toBeNull();expect(percentile(record('2d6',6))?.score).toBeCloseTo(71/72);expect(percentile(record('d6+2',3))?.score).toBeCloseTo(2.5/6);expect(percentile(record('d{1,1,6}',1))?.score).toBeCloseTo(1/3);expect(theoretical(low.normalizedExpression)).toBe(theoretical(low.normalizedExpression));expect(percentile({...low,finalResult:'text'}) as unknown).toBeNull();});
  it('keeps theoretical distributions exact and supplies estimated references',()=>{clearTheoreticalCache();const exact=record('d20',10),estimated=record('d6r',6);expect(theoretical(exact.normalizedExpression)?.exact).toBe(true);expect(theoretical(estimated.normalizedExpression)).toBeNull();expect(referenceDistribution(estimated.normalizedExpression)).toMatchObject({exact:false});expect(referenceDistribution(exact.normalizedExpression)).toBe(theoretical(exact.normalizedExpression));});
  it('calculates exact and estimated midpoint percentiles independently of lookup',()=>{const exact:Distribution={exact:true,entries:[{value:1,probability:1/3},{value:2,probability:1/3},{value:3,probability:1/3}],mean:2,range:[1,3]};expect(percentileFromDistribution(1,exact)).toMatchObject({score:1/6,tail:1/3,exact:true});expect(percentileFromDistribution(2,exact)).toMatchObject({score:1/2,tail:2/3,exact:true});const high=percentileFromDistribution(3,exact);expect(high).toMatchObject({tail:1/3,exact:true});expect(high!.score).toBeCloseTo(5/6);expect(percentileFromDistribution(4,exact)).toBeNull();const estimated:Distribution={exact:false,trials:20,entries:[{value:1,probability:.4},{value:3,probability:.6}],mean:2.2,range:[1,3]};expect(percentileFromDistribution(2,estimated)).toMatchObject({score:.4,tail:null,exact:false,trials:20,mean:2.2,range:[1,3]});});
  it('normalizes estimated rolls without exposing a rarity tail',()=>{clearTheoreticalCache();const result=percentile(record('d6r',6));expect(result).not.toBeNull();expect(result!.exact).toBe(false);expect(result!.score).toBeGreaterThanOrEqual(0);expect(result!.score).toBeLessThanOrEqual(1);expect(result!.tail).toBeNull();});
  it('tracks exact and estimated player participation separately',()=>{clearTheoreticalCache();const stats=playerStats([record('d20',10,'Exact'),record('d6r',6,'Estimated')]);expect(stats.find(player=>player.id==='Exact')).toMatchObject({qualifying:1,exactQualifying:1,estimatedQualifying:0});expect(stats.find(player=>player.id==='Estimated')).toMatchObject({qualifying:1,exactQualifying:0,estimatedQualifying:1});});
  it('keeps exact Fairness unavailable for estimated-only expressions',()=>{clearTheoreticalCache();const estimated=record('d6r',6);expect(fairness([estimated],estimated.normalizedExpression)).toBeNull();});
  it('clears both exact and reference distribution caches',()=>{clearTheoreticalCache();const exactRoll=record('d20',10),estimatedRoll=record('d6r',6),exact=theoretical(exactRoll.normalizedExpression),reference=referenceDistribution(estimatedRoll.normalizedExpression);expect(theoretical(exactRoll.normalizedExpression)).toBe(exact);expect(referenceDistribution(estimatedRoll.normalizedExpression)).toBe(reference);clearTheoreticalCache();expect(theoretical(exactRoll.normalizedExpression)).not.toBe(exact);expect(referenceDistribution(estimatedRoll.normalizedExpression)).not.toBe(reference);});
  it('groups players, expressions, dice, and observed outcomes',()=>{const rolls=[record('d6',1,'Joe'),record('d6',6,'Bill'),record('d20',20,'Joe')];expect(filterRolls(rolls,{player:'Joe'})).toHaveLength(2);const players=playerStats(rolls);expect(players.find(p=>p.name==='Joe')).toMatchObject({rolls:2,dice:2,expressions:2,mins:1,maxs:1});expect(expressionStats(rolls).find(e=>e.label.includes('d6'))?.expected).toBeCloseTo(3.5);expect(outcomeDistribution(rolls,'dice','d6').count).toBe(2);expect(outcomeDistribution(rolls,'results').mean).toBe(9);});
  it('exposes expression dialect and finite numeric result counts',()=>{const numeric=record('d6',1),symbolic=record('d{Miss,Hit}',1);const stats=expressionStats([numeric,symbolic]);expect(stats.find(item=>item.id===numeric.normalizedExpression)).toMatchObject({dialect:'nodice',numericCount:1});expect(stats.find(item=>item.id===symbolic.normalizedExpression)).toMatchObject({dialect:'nodice',numericCount:0,observed:null,min:null,max:null});});
  it('requires ten qualifying rolls for hot and cold',()=>{const short=playerStats([record('d6',1,'Joe'),record('d6',6,'Bill')]);expect(hotCold(short)).toBeNull();const long=playerStats([...Array.from({length:10},()=>record('d6',6,'Joe')),...Array.from({length:10},()=>record('d20',1,'Bill'))]);expect(hotCold(long)?.hot[0].name).toBe('Joe');expect(hotCold(long)?.cold[0].name).toBe('Bill');});
  it('compares exact frequencies',()=>{const rolls=[record('d6',1,'Joe',0),record('d6',6,'Joe',120_000)];const fair=fairness(rolls,rolls[0].normalizedExpression)!;expect(fair.sample).toBe(2);expect(fair.rows.find(r=>r.value===1)?.observed).toBe(1);expect(fair.rows[0].expected).toBeCloseTo(1/6);});
  it('gives fairness an expected range',()=>{const rolls=[record('d6',1,'Joe',0),record('d6',2,'Joe',86_400_000)];const fair=fairness(rolls,rolls[0].normalizedExpression)!;expect(fair.rows[0].range?.[0]).toBeGreaterThanOrEqual(0);expect(fair.cumulative).toHaveLength(2);});
});
