import { describe, expect, it } from 'vitest';
import { buildFairness } from './fairnessStats';
import { rollExpression } from './rollService';
import { normalizeExpression, type StoredRoll } from './sessionLedger';

let serial=0;
function roll(expression:string,face:number,time:number,player='Joe'):StoredRoll{const result=rollExpression({requestId:`fairness-${++serial}`,expression,visibility:'everyone',playerId:player,playerName:player},{integer:max=>(face-1)%max}).record;result.time=time;return {id:result.requestId,sessionId:'session',timestamp:time,rollerId:player,rollerName:player,expression,normalizedExpression:normalizeExpression(result),finalResult:result.value,resolution:result.resolution!,visibility:result.visibility,result};}

describe('Fairness analytics',()=>{
  it('accepts exact numeric theory and rejects estimated-only expressions',()=>{const exact=roll('d6',3,1),estimated=roll('d6r',6,2);expect(buildFairness([exact],exact.normalizedExpression)?.chart.exact).toBe(true);expect(buildFairness([estimated],estimated.normalizedExpression)).toBeNull();});
  it('calculates full observed frequencies, exact expectations, differences, and ranges',()=>{const rolls=[roll('d6',1,1),roll('d6',1,2),roll('d6',6,3)],data=buildFairness(rolls,rolls[0].normalizedExpression)!;expect(data.sample).toBe(3);const one=data.rows.find(row=>row.value===1)!;expect(one).toMatchObject({observed:2,observedRate:2/3,expected:1/6,difference:.5,supported:true});const margin=1.96*Math.sqrt((1/6)*(5/6)/3);expect(one.range?.[0]).toBeCloseTo(Math.max(0,1/6-margin));expect(one.range?.[1]).toBeCloseTo(Math.min(1,1/6+margin));});
  it('calculates means and exact midpoint percentile average',()=>{const rolls=[roll('d6',1,1),roll('d6',1,2),roll('d6',6,3)],data=buildFairness(rolls,rolls[0].normalizedExpression)!;expect(data.observedMean).toBeCloseTo(8/3);expect(data.expectedMean).toBeCloseTo(3.5);expect(data.meanDifference).toBeCloseTo(8/3-3.5);expect(data.averagePercentile).toBeCloseTo((1/12+1/12+11/12)/3);});
  it('retains outside-support numeric observations but excludes them from percentile trends',()=>{const supported=roll('d6',1,1),outside=roll('d6',1,2);outside.finalResult=99;outside.result.value=99;const data=buildFairness([supported,outside],supported.normalizedExpression)!;expect(data.sample).toBe(2);expect(data.outsideSupport).toBe(1);expect(data.rows.find(row=>row.value===99)).toMatchObject({observed:1,expected:0,supported:false,range:[0,0]});expect(data.cumulative).toHaveLength(1);expect(data.cumulative[0].roll).toBe(1);});
  it('orders chronologically for recent counts and cumulative coordinates without mutating input',()=>{const first=roll('d6',1,1),second=roll('d6',2,2),third=roll('d6',3,3),input=[third,first,second],data=buildFairness(input,first.normalizedExpression,{recentWindow:2})!;expect(input).toEqual([third,first,second]);expect(data.recent).toBe(2);expect(data.rows.find(row=>row.value===1)?.recentObserved).toBe(0);expect(data.rows.find(row=>row.value===2)?.recentObserved).toBe(1);expect(data.rows.find(row=>row.value===3)?.recentObserved).toBe(1);expect(data.cumulative.map(point=>point.timestamp)).toEqual([1,2,3]);});
  it('filters one player while preserving the same exact theory',()=>{const joe=roll('d6',1,1,'Joe'),bill=roll('d6',6,2,'Bill'),all=buildFairness([joe,bill],joe.normalizedExpression)!,onlyJoe=buildFairness([joe,bill],joe.normalizedExpression,{playerId:'Joe'})!;expect(all.sample).toBe(2);expect(all.players).toBe(2);expect(onlyJoe.sample).toBe(1);expect(onlyJoe.players).toBe(1);expect(onlyJoe.rows.find(row=>row.value===6)?.expected).toBe(all.rows.find(row=>row.value===6)?.expected);});
});
