import { useMemo, useState, type ReactNode } from 'react';
import { expressionStats } from './analytics';
import { PlayerName } from './components/PlayerName';
import { buildFairness, type FairnessRow, type FairnessTrendPoint } from './fairnessStats';
import type { StoredRoll } from './sessionLedger';
import { HelpTerm } from './components/HelpTerm';

const windows=[25,50,100,250];
const number=(value:number|null|undefined)=>value==null?'—':Number.isInteger(value)?String(value):value.toFixed(2);
const percent=(value:number|null|undefined)=>value==null?'—':`${(value*100).toFixed(1)}%`;
const points=(value:number)=>Math.abs(value)<.0005?'0.0 pp':`${value>0?'+':''}${(value*100).toFixed(1)} pp`;
const delta=(value:number|null)=>value==null?'—':Math.abs(value)<.005?'0':`${value>0?'+':''}${value.toFixed(2)}`;
const dialect=(value:'nodice'|'roll20')=>value==='roll20'?'Roll20':'No Dice';
function Card({label,value}:{label:string;value:ReactNode}){return <div className="stat-card"><small>{label}</small><strong>{value}</strong></div>;}

function FrequencyBar({observed,expected}:{observed:number;expected:number}){return <span className="fairness-bar-track" aria-hidden="true"><span className="fairness-bar" style={{width:`${Math.max(0,Math.min(100,observed*100))}%`}}/><span className="fairness-expected-marker" style={{left:`${Math.max(0,Math.min(100,expected*100))}%`}}/></span>;}
function FullTable({rows,sample}:{rows:FairnessRow[];sample:number}){return <div className="outcome-distribution fairness-distribution"><table><thead><tr><th>Outcome</th><th>Observed</th><th>Observed %</th><th><HelpTerm help="observedVsExpected">Observed vs. expected</HelpTerm></th><th>Expected %</th><th>Difference</th><th>Approx. 95% sample range</th></tr></thead><tbody>{rows.slice(0,200).map(row=><tr key={row.value} className={row.supported?undefined:'outside-support'}><td>{row.value}</td><td>{row.observed}</td><td>{percent(row.observedRate)}</td><td className="outcome-bar-cell"><FrequencyBar observed={row.observedRate} expected={row.expected}/></td><td>{percent(row.expected)}</td><td>{points(row.difference)}</td><td>{row.range?`${percent(row.range[0])}–${percent(row.range[1])}`:'—'}</td></tr>)}</tbody></table>{rows.length>200&&<p className="filter-summary">Showing first 200 of {rows.length} outcomes.</p>}{!sample&&<p className="filter-summary">Expected values remain available without an observed sample.</p>}</div>;}
function RecentTable({rows,recent}:{rows:FairnessRow[];recent:number}){return <div className="outcome-distribution fairness-distribution fairness-recent"><table><thead><tr><th>Outcome</th><th>Recent count</th><th>Recent %</th><th>Expected %</th><th>Difference</th></tr></thead><tbody>{rows.slice(0,200).map(row=><tr key={row.value} className={row.supported?undefined:'outside-support'}><td>{row.value}</td><td>{row.recentObserved}</td><td>{percent(row.recentRate)}</td><td>{percent(row.expected)}</td><td>{points(row.recentDifference)}</td></tr>)}</tbody></table>{rows.length>200&&<p className="filter-summary">Showing first 200 of {rows.length} outcomes.</p>}{!recent&&<p className="filter-summary">No recent observations are available.</p>}</div>;}

export function downsampleTrend(points:FairnessTrendPoint[],limit=300):FairnessTrendPoint[]{if(points.length<=limit)return points;if(limit<2)return [points.at(-1)!];const selected=[points[0]];for(let index=1;index<limit-1;index++)selected.push(points[Math.round(index*(points.length-1)/(limit-1))]);selected.push(points.at(-1)!);return selected;}
function Trend({points}:{points:FairnessTrendPoint[]}){if(points.length<2)return <p className="filter-summary">More comparable rolls are needed for a trend.</p>;const visible=downsampleTrend(points),lastRoll=points.at(-1)!.roll,coordinates=visible.map(point=>`${lastRoll<=1?0:(point.roll-1)/(lastRoll-1)*100},${100-point.average*100}`).join(' ');return <div className="fairness-trend-wrap"><svg className="fairness-trend" viewBox="0 0 100 100" role="img" aria-label="Cumulative average midpoint percentile over roll order"><line className="fairness-reference-line" x1="0" x2="100" y1="50" y2="50" data-reference="50%"/><polyline className="fairness-trend-line" points={coordinates}/><text x="1" y="8">100%</text><text x="1" y="48">50%</text><text x="1" y="98">0%</text></svg></div>;}

export function FairnessTab({rolls,roomId,viewerId}:{rolls:StoredRoll[];roomId:string;viewerId:string}){
  const [expressionId,setExpressionId]=useState(''),[playerId,setPlayerId]=useState(''),[recentWindow,setRecentWindow]=useState(100);
  const expressions=useMemo(()=>expressionStats(rolls).filter(expression=>expression.chart!==null),[rolls]);
  const selectedExpression=expressions.find(expression=>expression.id===expressionId)??expressions[0];
  const ambiguous=useMemo(()=>{const counts=new Map<string,number>();for(const expression of expressions)counts.set(expression.label,(counts.get(expression.label)??0)+1);return new Set([...counts].filter(([,count])=>count>1).map(([label])=>label));},[expressions]);
  const players=useMemo(()=>[...new Map(rolls.map(roll=>[roll.rollerId,roll.rollerName])).entries()].map(([id,name])=>({id,name})),[rolls]);
  const effectivePlayerId=players.some(player=>player.id===playerId)?playerId:'';
  const selectedPlayer=players.find(player=>player.id===effectivePlayerId);
  const data=useMemo(()=>selectedExpression?buildFairness(rolls,selectedExpression.id,{playerId:effectivePlayerId||undefined,recentWindow}):null,[rolls,selectedExpression,effectivePlayerId,recentWindow]);
  const expressionLabel=(expression:typeof expressions[number])=>`${expression.label}${ambiguous.has(expression.label)?` · ${dialect(expression.dialect)}`:''}`;
  return <section className="fairness-tab"><h2>Fairness explorer</h2>{!rolls.length?<p>No rolls yet.</p>:!expressions.length?<p>No expressions in this session have an exact numeric theoretical distribution available for Fairness analysis.</p>:<><p className="fairness-help">Fairness compares observed rolls with exact numeric theoretical distributions. Expressions requiring estimated distributions are not included.</p><div className="fairness-controls"><label><HelpTerm help="expression">Expression</HelpTerm><select value={selectedExpression.id} onChange={event=>setExpressionId(event.target.value)}>{expressions.map(expression=><option key={expression.id} value={expression.id}>{expressionLabel(expression)}</option>)}</select></label><label><HelpTerm help="population">Population</HelpTerm><select value={effectivePlayerId} onChange={event=>setPlayerId(event.target.value)}><option value="">All players</option>{players.map(player=><option key={player.id} value={player.id}>{player.name}</option>)}</select></label><label><HelpTerm help="recentWindow">Recent window</HelpTerm><select value={recentWindow} onChange={event=>setRecentWindow(Number(event.target.value))}>{windows.map(value=><option key={value} value={value}>{value}</option>)}</select></label></div>{selectedPlayer&&<p className="fairness-population">Population: <PlayerName roomId={roomId} viewerId={viewerId} playerId={selectedPlayer.id} name={selectedPlayer.name}/></p>}{data&&<>{!data.sample&&<p>No matching rolls for this player and expression.</p>}<div className="stat-grid fairness-summary"><Card label="Rolls" value={data.sample}/><Card label="Players" value={data.players}/><Card label="Observed mean" value={number(data.observedMean)}/><Card label="Expected mean" value={number(data.expectedMean)}/><Card label="Δ mean" value={delta(data.meanDifference)}/><Card label="Average percentile" value={percent(data.averagePercentile)}/><Card label="Outside theoretical support" value={data.outsideSupport}/></div><p className="fairness-help">Midpoint percentile averages are expected to approach 50% over large random samples, but finite samples can wander above or below it.</p><h3>Full sample</h3><FullTable rows={data.rows} sample={data.sample}/><p className="fairness-help">The range is an approximate per-outcome sampling band under the theoretical model. With many outcomes, some observations may fall outside a 95% band by chance.</p><h3><HelpTerm help="cumulativeAveragePercentile">Cumulative average percentile</HelpTerm></h3><Trend points={data.cumulative}/><h3>Recent {data.recent} rolls</h3><RecentTable rows={data.rows} recent={data.recent}/></>}</>}</section>;
}
