import { fireEvent, render, screen, within } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import type { Dialect } from './engine/ast';
import { FairnessTab } from './FairnessTab';
import { rollExpression } from './rollService';
import { normalizeExpression, type StoredRoll } from './sessionLedger';

let serial=0;
function roll(expression:string,face:number,time:number,player='Joe',dialect:Dialect='nodice'):StoredRoll{const result=rollExpression({requestId:`fairness-ui-${++serial}`,expression,dialect,visibility:'everyone',playerId:player,playerName:player},{integer:max=>(face-1)%max}).record;result.time=time;return {id:result.requestId,sessionId:'session',timestamp:time,rollerId:player,rollerName:player,expression,normalizedExpression:normalizeExpression(result),finalResult:result.value,resolution:result.resolution!,visibility:result.visibility,result};}
const summary=(label:string)=>within(document.querySelector('.fairness-summary') as HTMLElement).getByText(label).closest('.stat-card')?.querySelector('strong')?.textContent;

describe('FairnessTab',()=>{
  it('offers exact expressions only and automatically selects the most-used one',()=>{const d6=[roll('d6',1,1),roll('d6',2,2)],d20=roll('d20',10,3),estimated=roll('d6r',6,4);render(<FairnessTab rolls={[d20,estimated,...d6]} roomId="room" viewerId="viewer"/>);const select=screen.getByLabelText('Expression') as HTMLSelectElement;expect(within(select).getAllByRole('option').map(option=>option.textContent)).toEqual(['d6','d20']);expect(select.value).toBe(d6[0].normalizedExpression);expect(screen.getByText(/estimated distributions are not included/)).toBeTruthy();});
  it('disambiguates dialect-identical labels',()=>{render(<FairnessTab rolls={[roll('d6',1,1,'Joe','nodice'),roll('d6',2,2,'Joe','roll20')]} roomId="room" viewerId="viewer"/>);expect(within(screen.getByLabelText('Expression')).getAllByRole('option').map(option=>option.textContent)).toEqual(['d6 · No Dice','d6 · Roll20']);});
  it('filters to one population and displays PlayerName identity',()=>{const joe=roll('d6',1,1,'Joe'),bill=roll('d6',6,2,'Bill');render(<FairnessTab rolls={[joe,bill]} roomId="room" viewerId="viewer"/>);expect((screen.getByLabelText('Population') as HTMLSelectElement).value).toBe('');expect(summary('Rolls')).toBe('2');fireEvent.change(screen.getByLabelText('Population'),{target:{value:'Joe'}});expect(summary('Rolls')).toBe('1');expect(summary('Players')).toBe('1');const population=screen.getByText('Population:').parentElement!;expect(population.querySelector('.player-color-disk')).toBeTruthy();expect(population.textContent).toContain('Joe');});
  it('renders the summary, complete distribution columns, trend reference, and no verdict labels',()=>{const rolls=[roll('d6',1,1),roll('d6',6,2),roll('d6',3,3)];render(<FairnessTab rolls={rolls} roomId="room" viewerId="viewer"/>);for(const label of ['Rolls','Players','Observed mean','Expected mean','Δ mean','Average percentile','Outside theoretical support'])expect(summary(label)).not.toBeUndefined();const table=screen.getAllByRole('table')[0];expect(within(table).getAllByRole('columnheader').map(cell=>cell.textContent)).toEqual(['Outcome','Observed','Observed %','Distribution','Expected %','Difference','Approx. 95% sample range']);expect(screen.getByRole('img',{name:'Cumulative average midpoint percentile over roll order'})).toBeTruthy();expect(document.querySelector('[data-reference="50%"]')).toBeTruthy();for(const verdict of ['Fair','Unfair','Biased','Suspicious','Pass','Fail'])expect(screen.queryByText(verdict,{exact:true})).toBeNull();});
  it('changes the recent window and uses the last 25 observations',()=>{const rolls=Array.from({length:30},(_,index)=>roll('d6',index<5?1:6,index));render(<FairnessTab rolls={rolls} roomId="room" viewerId="viewer"/>);fireEvent.change(screen.getByLabelText('Recent window'),{target:{value:'25'}});expect(screen.getByRole('heading',{name:'Recent 25 rolls'})).toBeTruthy();const recent=screen.getAllByRole('table')[1],six=within(recent).getByText('6').closest('tr')!;expect(within(six).getAllByRole('cell')[1].textContent).toBe('25');});
  it('reports outside-support observations and preserves their table row',()=>{const normal=roll('d6',1,1),outside=roll('d6',1,2);outside.finalResult=99;outside.result.value=99;render(<FairnessTab rolls={[normal,outside]} roomId="room" viewerId="viewer"/>);expect(summary('Outside theoretical support')).toBe('1');const row=within(screen.getAllByRole('table')[0]).getByText('99').closest('tr')!;expect(within(row).getAllByRole('cell')[4].textContent).toBe('0.0%');});
  it('keeps controls when one player has no matching expression rolls',()=>{const d6=roll('d6',1,1,'Joe'),d20=roll('d20',10,2,'Bill');render(<FairnessTab rolls={[d6,d20]} roomId="room" viewerId="viewer"/>);fireEvent.change(screen.getByLabelText('Population'),{target:{value:'Bill'}});expect(screen.getByText('No matching rolls for this player and expression.')).toBeTruthy();expect(screen.getByLabelText('Expression')).toBeTruthy();});
  it('handles no eligible expressions and empty sessions',()=>{const {rerender}=render(<FairnessTab rolls={[roll('d6r',6,1)]} roomId="room" viewerId="viewer"/>);expect(screen.getByText('No expressions in this session have an exact numeric theoretical distribution available for Fairness analysis.')).toBeTruthy();expect(screen.queryByLabelText('Expression')).toBeNull();rerender(<FairnessTab rolls={[]} roomId="room" viewerId="viewer"/>);expect(screen.getByText('No rolls yet.')).toBeTruthy();});
});
