import { useMemo, useState } from 'react';
import type { StoredRoll } from './sessionLedger';
import { buildSequenceAnalysis, type ResultComparison } from './sequenceStats';
import { dieType, outcomeDistribution, playerStats, summary } from './analytics';

const display=(value:StoredRoll['finalResult'])=>Array.isArray(value)?`[${value.join(', ')}]`:String(value);
export function SequenceTab({rolls}:{rolls:StoredRoll[]}){
  const available=useMemo(()=>[...new Map(rolls.map(roll=>[roll.rollerId,roll.rollerName])).entries()].map(([id,name])=>({id,name})).sort((a,b)=>a.name.localeCompare(b.name)),[rolls]);
  const [chosen,setChosen]=useState<string[]|null>(null);
  const [pattern,setPattern]=useState('');
  const [comparison,setComparison]=useState<ResultComparison>('any');
  const [value,setValue]=useState('6');
  const [mode,setMode]=useState<'results'|'dice'>('results');
  const [die,setDie]=useState('');
  const [category,setCategory]=useState('');
  const [from,setFrom]=useState('');const [until,setUntil]=useState('');
  const selected=chosen??available.map(item=>item.id);
  const numeric=Number(value);
  const valid=comparison==='any'||(value.trim()!==''&&Number.isFinite(numeric));
  const analysis=useMemo(()=>valid?buildSequenceAnalysis(rolls,pattern,selected,mode==='dice'?'any':comparison,numeric):{entries:[],players:[],eligible:0,matching:0,error:'Enter a numeric result value.'},[rolls,pattern,chosen,comparison,numeric,valid,mode]);
  const matched=useMemo(()=>analysis.entries.map(entry=>entry.roll).filter(roll=>(!category||roll.result.interpretation===category)&&(!from||roll.timestamp>=new Date(from).getTime())&&(!until||roll.timestamp<new Date(until).getTime()+60_000)&&(mode!=='dice'||comparison==='any'||roll.resolution.dice.some(draw=>typeof draw.face==='number'&&(comparison==='='?draw.face===numeric:comparison==='<='?draw.face<=numeric:draw.face>=numeric)))),[analysis,category,from,until,mode,comparison,numeric]);
  const totals=useMemo(()=>summary(matched),[matched]);
  const playersStats=useMemo(()=>playerStats(matched),[matched]);
  const dieTypes=useMemo(()=>[...new Set(matched.flatMap(r=>r.resolution.dice.map(d=>dieType(r,d))))].sort(),[matched]);
  const outcomes=useMemo(()=>outcomeDistribution(matched,mode,mode==='dice'?dieTypes.includes(die)?die:dieTypes[0]:undefined),[matched,mode,die,dieTypes]);
  const qualifying=playersStats.reduce((n,p)=>n+p.qualifying,0);
  const average=qualifying?playersStats.reduce((n,p)=>n+(p.average??0)*p.qualifying,0)/qualifying:null;
  const categories=useMemo(()=>[...new Set(rolls.map(r=>r.result.interpretation).filter((v):v is string=>Boolean(v)))].sort(),[rolls]);
  const selectedSet=new Set(selected);
  const toggle=(id:string)=>setChosen(previous=>{const current=new Set(previous??available.map(item=>item.id));if(current.has(id))current.delete(id);else current.add(id);return [...current];});
  return <section className="sequence-tab" aria-label="Roll sequence">
    <p className="sequence-help">Match normalized expressions with a regular expression. The result filter uses the final outcome of each roll.</p>
    <div className="sequence-controls"><label>Expression regex<input type="text" value={pattern} onChange={event=>setPattern(event.target.value)} placeholder="^2d6(?:[+-]\d+)?$" maxLength={200} spellCheck={false}/></label><label>{mode==="dice"?"Die face":"Result"}<select value={comparison} onChange={event=>setComparison(event.target.value as ResultComparison)}><option value="any">Any</option><option value="=">=</option><option value="<=">≤</option><option value=">=">≥</option></select></label>{comparison!=='any'&&<label>Value<input type="number" value={value} onChange={event=>setValue(event.target.value)}/></label>}<label>Category<select value={category} onChange={event=>setCategory(event.target.value)}><option value="">Any</option>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>From<input type="datetime-local" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Until<input type="datetime-local" value={until} onChange={event=>setUntil(event.target.value)}/></label></div>
    <fieldset className="sequence-players"><legend>Players</legend><div className="sequence-player-actions"><button type="button" onClick={()=>setChosen(null)}>Select all</button><button type="button" onClick={()=>setChosen([])}>Clear all</button></div><div className="sequence-player-list">{available.map(item=><label key={item.id}><input type="checkbox" checked={selectedSet.has(item.id)} onChange={()=>toggle(item.id)}/>{item.name}</label>)}</div></fieldset>
    {analysis.error?<p className="input-error" role="alert">{analysis.error}</p>:<><p className="filter-summary">{matched.length} of {analysis.eligible} expression-matched rolls shown.</p><div className="stat-grid"><div className="stat-card"><small>Matched rolls / dice</small><strong>{totals.rolls} / {totals.dice}</strong></div><div className="stat-card"><small>Players / expressions</small><strong>{totals.players} / {totals.expressions}</strong></div><div className="stat-card"><small>Average percentile</small><strong>{average===null?'—':`${(average*100).toFixed(1)}%`}</strong></div><div className="stat-card"><small>Natural minimums / maximums</small><strong>{playersStats.reduce((n,p)=>n+p.mins,0)} / {playersStats.reduce((n,p)=>n+p.maxs,0)}</strong></div></div><div className="mode-tabs"><button type="button" aria-pressed={mode==='results'} onClick={()=>setMode('results')}>Results</button><button type="button" aria-pressed={mode==='dice'} onClick={()=>setMode('dice')}>Dice</button></div>{mode==='dice'&&<label>Die type <select value={dieTypes.includes(die)?die:dieTypes[0]??''} onChange={event=>setDie(event.target.value)}>{dieTypes.map(type=><option key={type}>{type}</option>)}</select></label>}<div className="stat-scroll"><table><thead><tr><th>Outcome</th><th>Count</th><th>Observed %</th></tr></thead><tbody>{outcomes.rows.slice(0,100).map(item=><tr key={`${typeof item.value}:${item.value}`}><td>{item.value}</td><td>{item.count}</td><td>{outcomes.count?`${(item.count/outcomes.count*100).toFixed(1)}%`:'—'}</td></tr>)}</tbody></table></div><div className="sequence-scroll"><table><thead><tr><th scope="col">#</th><th scope="col">Time</th><th scope="col">Expression</th>{analysis.players.map(player=><th scope="col" key={player.playerId}>{player.name}</th>)}</tr></thead><tbody>{matched.slice(0,500).map((roll,index)=><tr key={roll.id}><td>{index+1}</td><td>{new Date(roll.timestamp).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</td><td><code>{roll.normalizedExpression.slice(roll.normalizedExpression.indexOf(':')+1)}</code></td>{analysis.players.map(player=><td key={player.playerId}>{player.playerId===roll.rollerId?display(roll.finalResult):''}</td>)}</tr>)}</tbody><tfoot><tr><th colSpan={3}>Matching rolls</th>{analysis.players.map(player=><td key={player.playerId}>{player.matching}</td>)}</tr><tr><th colSpan={3}>Expression-matched rolls</th>{analysis.players.map(player=><td key={player.playerId}>{player.eligible}</td>)}</tr><tr><th colSpan={3}>Match rate</th>{analysis.players.map(player=><td key={player.playerId}>{(player.rate*100).toFixed(1)}%</td>)}</tr><tr><th colSpan={3}>Mean shown result</th>{analysis.players.map(player=><td key={player.playerId}>{player.mean?.toFixed(2)??'—'}</td>)}</tr></tfoot></table></div>{matched.length>500&&<p>Showing first 500 matching rolls.</p>}</>}
  </section>;
}
