export const STATISTICS_HELP = {
  expression: 'The dice formula being evaluated, such as d20+5 or 2d6. No Dice groups equivalent rolls by their normalized expression.',
  expressionRegex: 'A regular expression, or regex, is a text-matching pattern. Here it filters expressions by their normalized dice formula. For example, ^d20 matches d20 and d20+5.',
  result: 'The final value produced after the entire dice expression is evaluated. It is different from an individual die face rolled along the way.',
  rollFilter: 'Checks individual die draws inside a roll record, including rerolls and explosion draws. A matching die draw causes the whole roll record to match.',
  rollDie: 'Restricts the Roll filter to individual draws of this die type, such as d20. Leave it blank to match any die.',
  interpretationCategory: 'A text label assigned by an interpretation rule, such as Fail, Partial Success, or Success.',
  aggregate: 'How matching results are combined in a custom player statistic: Count, Sum, or Average.',
  mean: 'The arithmetic average: add the numeric values and divide by how many values there are.',
  median: 'The middle numeric value after the results are sorted. With an even number of results, it is halfway between the two middle values.',
  mode: 'The most frequently occurring outcome. More than one outcome can be tied for mode.',
  distribution: 'How results are spread among the possible outcomes. In observed tables, it shows how often each outcome actually occurred.',
  relativeFrequency: 'A quick visual comparison of how often outcomes occurred. The most common observed outcome gets a full-width bar; every other bar is scaled relative to it. Use Observed % for the actual percentage.',
  observedVsExpected: 'The filled bar uses a fixed 0%–100% scale and shows the observed percentage. The thin marker shows the exact expected percentage. Their separation shows the direction and size of the difference, not whether the dice are fair.',
  observed: 'What actually happened in the selected session or sample.',
  expected: 'What the exact probability model predicts over many rolls.',
  range: 'The span from the lowest numeric value to the highest.',
  distinctOutcomes: 'The number of different final results that appeared.',
  distinctFaces: 'The number of different individual die faces that appeared.',
  percentile: 'Shows where a result falls within that expression’s possible results. A result near the 90th percentile is higher than roughly 90% of the probability distribution.',
  midpointPercentile: 'A percentile adjusted for dice results that can tie. It counts half of the probability of the rolled value itself, placing tied outcomes near the middle of their probability mass.',
  averagePercentile: 'Converts each comparable result to its percentile within its own expression, then averages those percentiles. Around 50% is the long-run midpoint.',
  normalizedResult: 'A result expressed by where it falls in its own expression’s probability distribution. This allows very different dice expressions to be compared on the same percentile scale.',
  referenceDistribution: 'The probability distribution used to place a result on the percentile scale. No Dice uses an exact distribution when possible and may use an estimated one in views that allow estimates.',
  estimatedPercentile: 'A percentile approximated from simulated results because the exact distribution was too expensive to calculate. It is useful for relative position but is not treated as an exact rarity probability.',
  numericResults: 'Results that are finite numbers. Symbolic results and pool/array results can still appear in distributions but are excluded from numeric averages and ranges.',
  expectedMean: 'The arithmetic mean predicted by the exact theoretical probability distribution.',
  observedMean: 'The arithmetic mean of the numeric results that actually occurred.',
  deltaMean: 'Δ means “difference.” Here it is Observed mean minus Expected mean. Positive means the observed average was higher; negative means it was lower. It is descriptive, not a fairness verdict.',
  expectedRange: 'The lowest and highest numeric results possible according to the exact theoretical distribution.',
  observedRange: 'The lowest and highest numeric results that actually occurred in this sample.',
  exactTheoreticalDistribution: 'The mathematically calculated probability of every supported numeric outcome, with no simulation or estimation.',
  dialect: 'The dice-notation rules used to interpret the expression, such as No Dice syntax or Roll20 syntax.',
  analyzeDieType: 'In Dice mode, chooses which type of individual die draw is summarized after the roll records have been filtered. This is separate from Roll die, which controls the filter itself.',
  naturalMinimum: 'An individual die lands on its lowest possible face before modifiers or other expression math.',
  naturalMaximum: 'An individual die lands on its highest possible face before modifiers or other expression math.',
  interpretationCategories: 'The text labels produced by interpretation rules on final results, such as Fail, Partial Success, or Success.',
  observedPercentage: 'The share of the analyzed results that actually produced this outcome.',
  rarityTier: 'No Dice classifies exact probabilities of 5% or less as Unusual, 1% or less as Exceptional, 0.1% or less as Extraordinary, and 0.01% or less as Legendary. These thresholds are exact and unchanged.',
  rarestResult: 'The session’s least-probable qualifying final result using an exact probability calculation.',
  rarestDieFace: 'The least-probable qualifying individual die-face event that No Dice can calculate exactly.',
  rareRepeat: 'The least-probable qualifying streak of the same numeric result on repeated uses of the same expression by the same player. Other players or other expressions occurring between those rolls do not break that player’s expression-specific streak.',
  dicePool: 'Multiple dice rolled as one dice term, such as 4d6. Rerolls and explosion draws do not increase the initial pool size.',
  explosionChain: 'Additional draws generated from one original die by an exploding-die rule. The chain length counts additional draws, not the original die.',
  highStreak: 'Consecutive comparable rolls by that player above the 50th percentile. Other players rolling in between do not interrupt the player’s streak.',
  lowStreak: 'Consecutive comparable rolls by that player below the 50th percentile.',
  naturalMaximumStreak: 'Consecutive individual die draws by that player that landed on each die’s own highest possible face.',
  naturalMinimumStreak: 'Consecutive individual die draws by that player that landed on each die’s own lowest possible face.',
  fastestRollBurst: 'The largest number of session rolls occurring within any rolling 60-second window.',
  bandDuration: 'The amount of time represented by each Timeline row before consecutive empty rows are collapsed.',
  normalizedResultSize: 'Marker size represents the result’s percentile within its own expression: lower results are smaller and higher results are larger. Results without a usable numeric reference distribution use the middle size.',
  population: 'Which players’ rolls are included in this analysis. “All players” combines everyone who rolled the selected expression.',
  recentWindow: 'How many of the most recent matching rolls are used in the Recent section. It does not change the full-sample analysis.',
  sample: 'The numeric rolls currently included in the analysis for the selected expression and population.',
  theoreticalSupport: 'The set of numeric results allowed by the current exact probability model for this expression.',
  outsideTheoreticalSupport: 'Stored numeric results that do not appear in the current exact theoretical distribution. This can occur with legacy/imported data or after implementation changes and is reported rather than silently discarded.',
  differencePercentagePoints: 'Observed percentage minus Expected percentage. The result is shown in percentage points, abbreviated “pp.” For example, 30% observed versus 25% expected is +5 percentage points.',
  approximate95PercentSampleRange: 'An approximate range of observed percentages this single outcome would commonly produce in repeated samples of this size if the theoretical model were used. It is not a pass/fail test, and with many outcomes some values may fall outside their ranges by chance.',
  cumulativeAveragePercentile: 'After each comparable roll, No Dice converts that result to a percentile within this expression, then averages it with all earlier comparable rolls. The chart shows how that running average changes over time. Over many random rolls it tends toward 50%.',
  expectedPositionMarker: 'The thin marker shows the exact expected percentage; the filled bar shows the observed percentage.',
  includePrivateRolls: 'When off, Statistics uses only rolls addressed to Everyone so the GM and players can compare the same public dataset. When on, it also includes Self and GM-only rolls visible in your local ledger. Other viewers may have different private rolls.',
} as const;

export type StatisticsHelpKey = keyof typeof STATISTICS_HELP;
